/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as PortofolioRouteImport } from './routes/portofolio'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudioVideoRouteImport } from './routes/audio-video'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofolioRoute = PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVideoRoute = AudioVideoRouteImport.update({
  id: '/audio-video',
  path: '/audio-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRoute
  '/audio-video': typeof AudioVideoRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRoute
  '/audio-video': typeof AudioVideoRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artikel': typeof ArtikelRoute
  '/audio-video': typeof AudioVideoRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/portofolio': typeof PortofolioRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/training': typeof TrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artikel'
    | '/audio-video'
    | '/auth'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/artikel'
    | '/audio-video'
    | '/auth'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artikel'
    | '/audio-video'
    | '/auth'
    | '/book'
    | '/checkout'
    | '/portofolio'
    | '/sukses'
    | '/tentang'
    | '/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtikelRoute: typeof ArtikelRoute
  AudioVideoRoute: typeof AudioVideoRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  CheckoutRoute: typeof CheckoutRoute
  PortofolioRoute: typeof PortofolioRoute
  SuksesRoute: typeof SuksesRoute
  TentangRoute: typeof TentangRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofolio': {
      id: '/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof PortofolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-video': {
      id: '/audio-video'
      path: '/audio-video'
      fullPath: '/audio-video'
      preLoaderRoute: typeof AudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtikelRoute: ArtikelRoute,
  AudioVideoRoute: AudioVideoRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  CheckoutRoute: CheckoutRoute,
  PortofolioRoute: PortofolioRoute,
  SuksesRoute: SuksesRoute,
  TentangRoute: TentangRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
