/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbookSlugRouteImport } from './routes/ebook.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookSlugRoute = EbookSlugRouteImport.update({
  id: '/ebook/$slug',
  path: '/ebook/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/tentang': typeof TentangRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/ebook/$slug': typeof EbookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/tentang': typeof TentangRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/ebook/$slug': typeof EbookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/tentang': typeof TentangRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/ebook/$slug': typeof EbookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/katalog' | '/tentang' | '/checkout/$slug' | '/ebook/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/katalog' | '/tentang' | '/checkout/$slug' | '/ebook/$slug'
  id:
    | '__root__'
    | '/'
    | '/katalog'
    | '/tentang'
    | '/checkout/$slug'
    | '/ebook/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KatalogRoute: typeof KatalogRoute
  TentangRoute: typeof TentangRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  EbookSlugRoute: typeof EbookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook/$slug': {
      id: '/ebook/$slug'
      path: '/ebook/$slug'
      fullPath: '/ebook/$slug'
      preLoaderRoute: typeof EbookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KatalogRoute: KatalogRoute,
  TentangRoute: TentangRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  EbookSlugRoute: EbookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
